### ISSUE TITLE
ARMv7 not supported.

### ISSUE THREAD

**Issue by verticalsync** [pyoncord/Bunny#17] opened 2024-04-05 21:22 UTC
ARMv7 isn't supported on vendetta since a while ago, so I haven't been able to use it, however is it possible to fix this somehow? This should also be clarified somewhere that ARMv7 doesn't work anymore.

**Comment by amsryq** [comment] 2024-05-03 17:28
Can you please give more details about the problem?
What kind of error did you face?
Can you provide crash logs if possible?

**Comment by verticalsync** [comment] 2024-05-05 17:02
> Can you please give more details about the problem?
> What kind of error did you face?
> Can you provide crash logs if possible?

no crash logs, no error it just closes

**Comment by programmer2514** [comment] 2024-05-06 16:06
I have begun having the same issue, starting after the April 2024 Google Play system update. The app simply crashes on launch with no error message or logs whatsoever.

My device is a Samsung Galaxy A13 5G (armv7) running Android 13 and One UI 5.1.

**Comment by Ushie** [comment] 2024-05-06 16:12
I think this either is or is similar to what @palmdevs pointed out months ago, where things randomly stopped working on ARMv7 Samsung devices, hopefully Palm would be able to share helpful info if they still remember any

**Comment by PalmDevs** [comment] 2024-05-06 17:08
> I think this either is or is similar to what @palmdevs pointed out months ago, where things randomly stopped working on ARMv7 Samsung devices, hopefully Palm would be able to share helpful info if they still remember any

Something might've changed about React Native a few versions back (or maybe LSPosed just doesn't want to work on ARMv7). The module complains about not being able to find a method to inject to, even though when listing methods manually using a modified module works fine, as in the method is listed. [These are the problematic lines in the Xposed module.](https://github.com/pyoncord/BunnyXposed/blob/master/app%2Fsrc%2Fmain%2Fkotlin%2Fio%2Fgithub%2Fpyoncord%2Fxposed%2FMain.kt#L67-L78)

Injecting alternative methods without the `jni` prefix kind of works, but it causes an issue where no icons are displayed.

![No icons issue](https://github.com/pyoncord/Bunny/assets/67689562/22709fd3-cd38-4c5c-ba22-57d4745a895c)

Opening some pages (notably forum posts) results in a hard crash with these stack traces.

```
05-07 00:18:05.638 26707 26707 E AndroidRuntime: FATAL EXCEPTION: main
05-07 00:18:05.638 26707 26707 E AndroidRuntime: Process: com.discord, PID: 26707
05-07 00:18:05.638 26707 26707 E AndroidRuntime: java.lang.NullPointerException
05-07 00:18:05.638 26707 26707 E AndroidRuntime:        at com.discord.react_asset_fetcher.ReactAssetUtilsKt$setReactIcon$2$1$1.invokeSuspend(SourceFile:80)
05-07 00:18:05.638 26707 26707 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.a.resumeWith(SourceFile:12)
05-07 00:18:05.638 26707 26707 E AndroidRuntime:        at kotlinx.coroutines.k.run(SourceFile:124)
05-07 00:18:05.638 26707 26707 E AndroidRuntime:        at gk.o$a.run(SourceFile:4)
05-07 00:18:05.638 26707 26707 E AndroidRuntime:        at ik.k.run(SourceFile:3)
05-07 00:18:05.638 26707 26707 E AndroidRuntime:        at ik.a.I(SourceFile:1)
05-07 00:18:05.638 26707 26707 E AndroidRuntime:        at ik.a$c.d(SourceFile:15)
05-07 00:18:05.638 26707 26707 E AndroidRuntime:        at ik.a$c.p(SourceFile:29)
05-07 00:18:05.638 26707 26707 E AndroidRuntime:        at ik.a$c.run(Unknown Source:0)
05-07 00:18:05.638 26707 26707 E AndroidRuntime:        Suppressed: gk.i: [k1{Cancelling}@e880b04, Dispatchers.Main.immediate]
```

**Comment by PalmDevs** [comment] 2024-05-06 17:22
If you really want to use Bunny, I recommend downgrading to somewhere around `210.x`. As far as I can remember, those versions work.

**Comment by programmer2514** [comment] 2024-05-06 17:32
I tried it on v210.10 and v207.23, both with the same result - instant crashing on startup.

**Comment by PalmDevs** [comment] 2024-05-06 17:34
That's very odd, used to work fine for me. I'll try if I have time.

**Comment by programmer2514** [comment] 2024-05-06 17:37
Something else that may be useful - Bunny was working just fine for me on v227.12 just yesterday night. I did not update the app or do anything else since then except for installing the latest Google Play system update and rebooting my phone.

**Comment by PalmDevs** [comment] 2024-05-16 18:44
I can confirm that this is an issue with Google Play System Updates. I've recently factory reset my phone and I am running on July 2023 updates, BunnyXposed works correctly.

**Comment by blabw** [comment] 2024-05-18 20:16
> I can confirm that this is an issue with Google Play System Updates. I've recently factory reset my phone and I am running on July 2023 updates, BunnyXposed works correctly.

I made a Google play system update but it still instantly crashes when I try to launch it

**Comment by PalmDevs** [comment] 2024-06-21 06:49
For future reference, the issue stems from a Google Play system update for the `com.android.art` component. If you have superuser, you can manually revert the update for that specific component by deleting `/data/apex/active/com.android.art@[...].apex`.

Tested on May 2024 GPSU, Android 14.

---

@amsyarasyiq You can probably close this as not planned.

**Comment by verticalsync** [comment] 2024-06-21 10:05
> For future reference, the issue stems from a Google Play system update for the `com.android.art` component. If you have superuser, you can manually revert the update for that specific component by deleting `/data/apex/active/com.android.art@[...].apex`.
> 
> Tested on May 2024 GPSU, Android 14.
> 
> ---
> 
> @amsyarasyiq You can probably close this as not planned.

Unfortunately, I don't have superuser, but alright.

**Closed as not planned** 2024-06-24 17:34 UTC
Labels: bug

**Comment by tt-thoma** [comment] 2024-08-22 05:40
I know this will likely not be fixed but is there any way to change the methods used in Bunny to fix this issue ? Or has the update changed too much

**Comment by Ushie** [comment] 2024-08-22 09:18
This issue has already been fixed in https://github.com/pyoncord/BunnyXposed/pull/4

**Comment by tt-thoma** [comment] 2024-10-12 17:48
Well not for me apparently...
Edit: Nevermind, I cleared cache and data and it works now
