### ISSUE TITLE
bug: phone detects as harmful

### ISSUE THREAD

**Issue by AugustIsNice123** [pyoncord/Bunny#82] opened 2024-09-09 03:08 UTC
**Describe the bug**
My phone says that the app is harmful

**To Reproduce**
1. Go to 'Bunny'
2. Click on 'Bunny Manager'
3. Scroll down to 'The Releases'
4. Click on 'manager.apk'
5. phone says it's harmful
6. I click install anyway
7. Go to files to download manager
8. Click on manager
9. Wait a bit
11. See error (play protect says it's harmful)

**Expected behavior**
Install the manager and get bunny

**Device Information (please complete the following information):**
 - Device: Samsung S23
 - OS: Android 14
 - Discord Version Latest

**Checklists**
- [ ✔️ ] I understand that this is a bug report and not a place to request new features or plugins
- [ ✔️ ] I understand that this is no place to report bugs produced by a plugin
- [ X ] I can reproduce this bug in Bunny's safe mode AND unable to reproduce it in vanilla/unmodded Discord

**Comment by MrK004** [comment] 2024-09-09 05:32
Same on my end. (S24 Ultra)

**Comment by Rico040** [comment] 2024-09-09 05:33
duplicate of https://github.com/pyoncord/BunnyManager/issues/24
as i already mentioned, this is false positive.

**Closed as not planned** 2024-09-09 07:46 UTC
Labels: bug
